### ISSUE TITLE
[feat] 순환그리드

### ISSUE THREAD

**Issue by jife-archive** [Nexters/Don-t-Forget---iOS#23]
## 어떤 기능인가요?

> 생일 설정할때 360도 순환으로 그리드를 구성할려고합니다.

## 작업 상세 내용

- [ ] 순환그리드

**Comment by dayo2n** [comment]
아 360도 순환
끝에 도달하면 다시 첫 아이템부터 보여주면 되지 않을까? 나도 해보지 않았지만 ㅎ
이렇게 생각하면 그럼 몇 번이나 순환했는지 카운트해야 할 텐데 내부적으로 2번째 순환이라고 해서 2000년대로 설정될 순 있겠지만 유저입장에서는 계속 00~99로만 보이는지라 1900년대인지 2000년대인지 알기 어려울 것 같아... 
연도를 4자리로 표시하는 게 맞을 것 같은데 동의한다면 디자이너들과의 논의가 어떠한쥐!??
